name: Bug Report
description: Create a bug report for this plugin.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report! To ensure this hasn’t already been reported, please first search [existing issues](https://github.com/putyourlightson/craft-blitz/issues?q=is%3Aissue) and ensure you’re running the latest version.

        To rule out that this isn’t a setup or configuration issue, please read the [Best Practices](https://putyourlightson.com/plugins/blitz#best-practices) and [Common Issues](https://putyourlightson.com/plugins/blitz#common-issues) sections of the docs.
        
        If you still believe you’ve found a bug, please provide a clear and concise description, including:
        - What is happening and what you expected to happen.
        - Steps to reproduce the issue.
        - Screenshots, if applicable.
  - type: textarea
    id: body
    attributes:
      label: Bug Report
      description: Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Diagnostics Report
      description: Provide a diagnostics report that can be generated in the Blitz Diagnostics utility in versions 4.17.0 and 5.2.0 and above. If this is not available then provide, at the very least, the versions of Blitz, Craft and PHP.
    validations:
      required: true
