name: Bug Report
description: Create a bug report for this plugin.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report! To ensure this hasn’t already been reported, please first search [existing issues](https://github.com/putyourlightson/craft-blitz/issues?q=is%3Aissue).

        To rule out that this isn’t a setup or configuration issue, please read the [Best Practices](https://putyourlightson.com/plugins/blitz#best-practices) and [Common Issues](https://putyourlightson.com/plugins/blitz#common-issues) sections of the docs.
        
        If you still believe you’ve found a bug, please provide a clear and concise description, including:
        - What is happening and what you expected to happen.
        - Steps to reproduce the issue.
        - Screenshots, if applicable.
  - type: textarea
    id: body
    attributes:
      label: 'Bug report'
    validations:
      required: true
  - type: input
    id: pluginVersion
    attributes:
      label: Plugin version
    validations:
      required: true
  - type: input
    id: craftVersion
    attributes:
      label: Craft CMS version
    validations:
      required: true
  - type: input
    id: phpVersion
    attributes:
      label: PHP version
    validations:
      required: true
