name: Feature Request
description: Suggest a new feature for this plugin.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! To ensure that this isn’t already on our radar, please first search the [existing issues](https://github.com/putyourlightson/craft-blitz/issues?q=is%3Aissue).

        If you still believe that you have a new feature request, please provide a clear and concise description, including:
        - What problem you believe your feature request can solve.
        - Any alternative solutions or features you have already considered.  

  - type: textarea
    id: body
    attributes:
      label: 'Description'
    validations:
      required: true
  - type: input
    id: pluginVersion
    attributes:
      label: Plugin version
    validations:
      required: true
