name: Support Request
description: Ask a question about this plugin.
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a support request! To ensure that your question hasn’t already been answered, please first search the [existing issues](https://github.com/putyourlightson/craft-blitz/issues?q=is%3Aissue).
        
        If your question is still unanswered, please provide a clear and concise description. Note that we are diligent about documentation, so please check whether your question is answered by the [plugin docs](https://putyourlightson.com/plugins/blitz) before submitting.
  - type: textarea
    id: body
    label: 'Description'
    validations:
      required: true
  - type: input
    id: pluginVersion
    attributes:
      label: Plugin version
    validations:
      required: true
